[package]
name = "discord-auto-translator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
regex = "1"
serenity = { version = "0.11", default-features = false, features = ["client", "cache", "gateway", "rustls_backend", "model"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
deepl = "0.4.0"
url = "2.3.1"